//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatroom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public int SenderId { get; set; }
        public int RecieverId { get; set; }
        public string Content { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string SenderName { get; set; }
        public string ReceiverName { get; set; }
    
        public virtual UserData UserData { get; set; }
        public virtual UserData UserData1 { get; set; }
    }
}
